### ISSUE TITLE
Question: Why not an HOC or FAC?

### ISSUE THREAD

**Issue by zsherman** [ReactTraining/react-network#5]
Hey @ryanflorence just installed this and it's working great, thanks for open sourcing 👍. One quick question for you, I found the render logic a little strange at first and was just curious why you chose not to implement this as either a set of higher-order components or a function/child, maybe like:

```
<Online>
  <p>You're online.</p>
</Online>
<Offline>
  <p>You're offline.</p>
</Offline>
```

or

```
<Network>
  {({ online }) => (
    <p>{online ? 'Party time' : 'No party for you'}</p>
  )}
/>
```

or even

```
const MyApp = ({ online }) => <p>{online ? 'Party time' : 'No party for you'}</p>
export default withNetwork(MyApp)
```

Might be an obvious answer I'm missing, was just curious.

**Comment by Andreyco** [comment]
This is the reason.
https://cdb.reacttraining.com/use-a-render-prop-50de598f11ce

**Comment by zsherman** [comment]
Good read, thanks @Andreyco.
